// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:efe923c4-b626-4506-8597-89a79946ec19",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_VjnYbQjPN",
    "aws_user_pools_web_client_id": "pl71gfm4m16628hodd27prdv2",
    "aws_appsync_graphqlEndpoint": "https://tkv5ar2zvnbjpietwlkwazoypa.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
